name: CI-CD-Demo-Dag
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
    hogent-cicd-demo:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repo
          uses: actions/checkout@v4
        - name: Install dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: "10.0.x"
        - name: Build app
          run: dotnet build PG3CICDGent/PG3CICDGent.slnx
        - name: Run tests
          run: dotnet test PG3CICDGent/Test*/*.csproj