name: CI-CD-Demo-Dag
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
    prep-env:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repo
          uses: actions/checkout@v4
        - name: Install dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: "10.0.x"
    build:
      needs: prep-env
      runs-on: ubuntu-latest
      steps:
        - name: Build app
          run: dotnet build PG3CICDGent/PG3CICDGent.slnx
    test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Run tests
          run: dotnet test PG3CICDGent/Test*/*.csproj
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Publish
          run: dotnet publish PG3CICDGent/PG3CICDGent/PG3CICDGent.csproj -o ${{ github.workspace }}/publish
        - name: Deploy
          uses: azure/webapps-deploy@v3
          with:
            app-name: "hogent-pg3-dag-cicd"
            publish-profile: ${{ secrets.API_PUBLISH_PROFILE_AZURE }} 
            package: ${{ github.workspace }}/publish      